---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2026-01-01T11:05:49Z"
  labels:
    kubernetes.io/metadata.name: wordpress
  name: wordpress
  resourceVersion: "1330"
  uid: 1eebe08a-dc00-40d3-9d82-8df0c47f5cbf
spec:
  finalizers:
    - kubernetes
status:
  phase: Active
