---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: wordpress
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30000
        hostPort: 8080
    extraMounts:
      - hostPath: ./data
        containerPath: /home/ida/Apps/config-repo/wordpress/data
  - role: worker
  - role: worker
